import { Atom, Cloud, Droplet, Gauge, Sun, Thermometer, Volume2, Wind } from 'lucide-react';

export interface SensorData {
  icon: React.ReactNode;
  name: string;
  value: string;
  unit: string;
  status: 'Good' | 'Warning';
  description: string;
}

export interface CityData {
  name: string;
  sensors: SensorData[];
}

const sensorDescriptions = {
  temp: 'Temperatura powietrza - kluczowy parametr wpływający na komfort cieplny. Optymalna temperatura w pomieszczeniach to 20-22°C.',
  co2: 'Stężenie dwutlenku węgla - wskaźnik jakości powietrza. Poziomy powyżej 1000 ppm mogą powodować zmęczenie i trudności w koncentracji.',
  voc: 'Lotne związki organiczne - substancje chemiczne mogące negatywnie wpływać na zdrowie. Niskie poziomy są kluczowe dla dobrej jakości powietrza.',
  pm25: 'Pył zawieszony PM2.5 - drobne cząstki mogące przenikać do płuc. Poziomy poniżej 25 µg/m³ są uznawane za bezpieczne.',
  pm10: 'Pył zawieszony PM10 - większe cząstki pyłu. Poziomy poniżej 50 µg/m³ są uznawane za bezpieczne dla zdrowia.',
  humidity:
    'Wilgotność powietrza - wpływa na komfort i zdrowie. Optymalne poziomy mieszczą się w zakresie 40-60%.',
  noise:
    'Poziom hałasu - wpływa na komfort i koncentrację. Poziomy powyżej 65 dBA mogą być uciążliwe.',
  pressure:
    'Ciśnienie atmosferyczne - wpływa na samopoczucie. Nagłe zmiany mogą powodować dolegliwości u osób wrażliwych.',
  light:
    'Natężenie światła - wpływa na komfort wizualny i produktywność. Optymalne poziomy zależą od rodzaju wykonywanej pracy.',
};

export const sensorsData: Record<string, CityData> = {
  gdansk: {
    name: 'Gdańsk',
    sensors: [
      {
        icon: <Thermometer className="w-5 h-5" />,
        name: 'Temp',
        value: '21.5',
        unit: '°C',
        status: 'Good',
        description: sensorDescriptions.temp,
      },
      {
        icon: <Cloud className="w-5 h-5" />,
        name: 'CO₂',
        value: '508',
        unit: 'ppm',
        status: 'Good',
        description: sensorDescriptions.co2,
      },
      {
        icon: <Wind className="w-5 h-5" />,
        name: 'VOC',
        value: '48',
        unit: 'ppb',
        status: 'Good',
        description: sensorDescriptions.voc,
      },
      {
        icon: <Atom className="w-5 h-5" />,
        name: 'PM 2.5',
        value: '12',
        unit: 'µg/m³',
        status: 'Good',
        description: sensorDescriptions.pm25,
      },
      {
        icon: <Atom className="w-5 h-5" />,
        name: 'PM10',
        value: '15',
        unit: 'µg/m³',
        status: 'Good',
        description: sensorDescriptions.pm10,
      },
      {
        icon: <Droplet className="w-5 h-5" />,
        name: 'Humidity',
        value: '45',
        unit: '%',
        status: 'Good',
        description: sensorDescriptions.humidity,
      },
      {
        icon: <Volume2 className="w-5 h-5" />,
        name: 'Noise',
        value: '52',
        unit: 'dBA',
        status: 'Warning',
        description: sensorDescriptions.noise,
      },
      {
        icon: <Gauge className="w-5 h-5" />,
        name: 'Pressure',
        value: '1013',
        unit: 'hPa',
        status: 'Good',
        description: sensorDescriptions.pressure,
      },
      {
        icon: <Sun className="w-5 h-5" />,
        name: 'Light',
        value: '75',
        unit: '%',
        status: 'Good',
        description: sensorDescriptions.light,
      },
    ],
  },
  gdynia: {
    name: 'Gdynia',
    sensors: [
      {
        icon: <Thermometer className="w-5 h-5" />,
        name: 'Temp',
        value: '19.8',
        unit: '°C',
        status: 'Good',
        description: sensorDescriptions.temp,
      },
      {
        icon: <Cloud className="w-5 h-5" />,
        name: 'CO₂',
        value: '485',
        unit: 'ppm',
        status: 'Good',
        description: sensorDescriptions.co2,
      },
      {
        icon: <Wind className="w-5 h-5" />,
        name: 'VOC',
        value: '52',
        unit: 'ppb',
        status: 'Warning',
        description: sensorDescriptions.voc,
      },
      {
        icon: <Atom className="w-5 h-5" />,
        name: 'PM 2.5',
        value: '8',
        unit: 'µg/m³',
        status: 'Good',
        description: sensorDescriptions.pm25,
      },
      {
        icon: <Atom className="w-5 h-5" />,
        name: 'PM10',
        value: '11',
        unit: 'µg/m³',
        status: 'Good',
        description: sensorDescriptions.pm10,
      },
      {
        icon: <Droplet className="w-5 h-5" />,
        name: 'Humidity',
        value: '55',
        unit: '%',
        status: 'Good',
        description: sensorDescriptions.humidity,
      },
      {
        icon: <Volume2 className="w-5 h-5" />,
        name: 'Noise',
        value: '48',
        unit: 'dBA',
        status: 'Good',
        description: sensorDescriptions.noise,
      },
      {
        icon: <Gauge className="w-5 h-5" />,
        name: 'Pressure',
        value: '1015',
        unit: 'hPa',
        status: 'Good',
        description: sensorDescriptions.pressure,
      },
      {
        icon: <Sun className="w-5 h-5" />,
        name: 'Light',
        value: '82',
        unit: '%',
        status: 'Good',
        description: sensorDescriptions.light,
      },
    ],
  },
  sopot: {
    name: 'Sopot',
    sensors: [
      {
        icon: <Thermometer className="w-5 h-5" />,
        name: 'Temp',
        value: '20.2',
        unit: '°C',
        status: 'Good',
        description: sensorDescriptions.temp,
      },
      {
        icon: <Cloud className="w-5 h-5" />,
        name: 'CO₂',
        value: '495',
        unit: 'ppm',
        status: 'Good',
        description: sensorDescriptions.co2,
      },
      {
        icon: <Wind className="w-5 h-5" />,
        name: 'VOC',
        value: '45',
        unit: 'ppb',
        status: 'Good',
        description: sensorDescriptions.voc,
      },
      {
        icon: <Atom className="w-5 h-5" />,
        name: 'PM 2.5',
        value: '10',
        unit: 'µg/m³',
        status: 'Good',
        description: sensorDescriptions.pm25,
      },
      {
        icon: <Atom className="w-5 h-5" />,
        name: 'PM10',
        value: '13',
        unit: 'µg/m³',
        status: 'Good',
        description: sensorDescriptions.pm10,
      },
      {
        icon: <Droplet className="w-5 h-5" />,
        name: 'Humidity',
        value: '50',
        unit: '%',
        status: 'Good',
        description: sensorDescriptions.humidity,
      },
      {
        icon: <Volume2 className="w-5 h-5" />,
        name: 'Noise',
        value: '43',
        unit: 'dBA',
        status: 'Good',
        description: sensorDescriptions.noise,
      },
      {
        icon: <Gauge className="w-5 h-5" />,
        name: 'Pressure',
        value: '1014',
        unit: 'hPa',
        status: 'Good',
        description: sensorDescriptions.pressure,
      },
      {
        icon: <Sun className="w-5 h-5" />,
        name: 'Light',
        value: '68',
        unit: '%',
        status: 'Good',
        description: sensorDescriptions.light,
      },
    ],
  },
  slupsk: {
    name: 'Słupsk',
    sensors: [
      {
        icon: <Thermometer className="w-5 h-5" />,
        name: 'Temp',
        value: '19.5',
        unit: '°C',
        status: 'Good',
        description: sensorDescriptions.temp,
      },
      {
        icon: <Cloud className="w-5 h-5" />,
        name: 'CO₂',
        value: '490',
        unit: 'ppm',
        status: 'Good',
        description: sensorDescriptions.co2,
      },
      {
        icon: <Wind className="w-5 h-5" />,
        name: 'VOC',
        value: '47',
        unit: 'ppb',
        status: 'Good',
        description: sensorDescriptions.voc,
      },
      {
        icon: <Atom className="w-5 h-5" />,
        name: 'PM 2.5',
        value: '11',
        unit: 'µg/m³',
        status: 'Good',
        description: sensorDescriptions.pm25,
      },
      {
        icon: <Atom className="w-5 h-5" />,
        name: 'PM10',
        value: '14',
        unit: 'µg/m³',
        status: 'Good',
        description: sensorDescriptions.pm10,
      },
      {
        icon: <Droplet className="w-5 h-5" />,
        name: 'Humidity',
        value: '52',
        unit: '%',
        status: 'Good',
        description: sensorDescriptions.humidity,
      },
      {
        icon: <Volume2 className="w-5 h-5" />,
        name: 'Noise',
        value: '45',
        unit: 'dBA',
        status: 'Good',
        description: sensorDescriptions.noise,
      },
      {
        icon: <Gauge className="w-5 h-5" />,
        name: 'Pressure',
        value: '1012',
        unit: 'hPa',
        status: 'Good',
        description: sensorDescriptions.pressure,
      },
      {
        icon: <Sun className="w-5 h-5" />,
        name: 'Light',
        value: '70',
        unit: '%',
        status: 'Good',
        description: sensorDescriptions.light,
      },
    ],
  },
  ustka: {
    name: 'Ustka',
    sensors: [
      {
        icon: <Thermometer className="w-5 h-5" />,
        name: 'Temp',
        value: '19.2',
        unit: '°C',
        status: 'Good',
        description: sensorDescriptions.temp,
      },
      {
        icon: <Cloud className="w-5 h-5" />,
        name: 'CO₂',
        value: '475',
        unit: 'ppm',
        status: 'Good',
        description: sensorDescriptions.co2,
      },
      {
        icon: <Wind className="w-5 h-5" />,
        name: 'VOC',
        value: '44',
        unit: 'ppb',
        status: 'Good',
        description: sensorDescriptions.voc,
      },
      {
        icon: <Atom className="w-5 h-5" />,
        name: 'PM 2.5',
        value: '9',
        unit: 'µg/m³',
        status: 'Good',
        description: sensorDescriptions.pm25,
      },
      {
        icon: <Atom className="w-5 h-5" />,
        name: 'PM10',
        value: '12',
        unit: 'µg/m³',
        status: 'Good',
        description: sensorDescriptions.pm10,
      },
      {
        icon: <Droplet className="w-5 h-5" />,
        name: 'Humidity',
        value: '58',
        unit: '%',
        status: 'Good',
        description: sensorDescriptions.humidity,
      },
      {
        icon: <Volume2 className="w-5 h-5" />,
        name: 'Noise',
        value: '42',
        unit: 'dBA',
        status: 'Good',
        description: sensorDescriptions.noise,
      },
      {
        icon: <Gauge className="w-5 h-5" />,
        name: 'Pressure',
        value: '1011',
        unit: 'hPa',
        status: 'Good',
        description: sensorDescriptions.pressure,
      },
      {
        icon: <Sun className="w-5 h-5" />,
        name: 'Light',
        value: '65',
        unit: '%',
        status: 'Good',
        description: sensorDescriptions.light,
      },
    ],
  },
  warszawa: {
    name: 'Warszawa',
    sensors: [
      {
        icon: <Thermometer className="w-5 h-5" />,
        name: 'Temp',
        value: '20.2',
        unit: '°C',
        status: 'Good',
        description: sensorDescriptions.temp,
      },
      {
        icon: <Cloud className="w-5 h-5" />,
        name: 'CO₂',
        value: '540',
        unit: 'ppm',
        status: 'Good',
        description: sensorDescriptions.co2,
      },
      {
        icon: <Wind className="w-5 h-5" />,
        name: 'VOC',
        value: '55',
        unit: 'ppb',
        status: 'Good',
        description: sensorDescriptions.voc,
      },
      {
        icon: <Atom className="w-5 h-5" />,
        name: 'PM 2.5',
        value: '16.8',
        unit: 'µg/m³',
        status: 'Good',
        description: sensorDescriptions.pm25,
      },
      {
        icon: <Atom className="w-5 h-5" />,
        name: 'PM10',
        value: '29.4',
        unit: 'µg/m³',
        status: 'Good',
        description: sensorDescriptions.pm10,
      },
      {
        icon: <Droplet className="w-5 h-5" />,
        name: 'Humidity',
        value: '52',
        unit: '%',
        status: 'Good',
        description: sensorDescriptions.humidity,
      },
      {
        icon: <Volume2 className="w-5 h-5" />,
        name: 'Noise',
        value: '64',
        unit: 'dBA',
        status: 'Warning',
        description: sensorDescriptions.noise,
      },
      {
        icon: <Gauge className="w-5 h-5" />,
        name: 'Pressure',
        value: '1016',
        unit: 'hPa',
        status: 'Good',
        description: sensorDescriptions.pressure,
      },
      {
        icon: <Sun className="w-5 h-5" />,
        name: 'Light',
        value: '78',
        unit: '%',
        status: 'Good',
        description: sensorDescriptions.light,
      },
    ],
  },
  krakow: {
    name: 'Kraków',
    sensors: [
      {
        icon: <Thermometer className="w-5 h-5" />,
        name: 'Temp',
        value: '21.1',
        unit: '°C',
        status: 'Good',
        description: sensorDescriptions.temp,
      },
      {
        icon: <Cloud className="w-5 h-5" />,
        name: 'CO₂',
        value: '585',
        unit: 'ppm',
        status: 'Warning',
        description: sensorDescriptions.co2,
      },
      {
        icon: <Wind className="w-5 h-5" />,
        name: 'VOC',
        value: '62',
        unit: 'ppb',
        status: 'Warning',
        description: sensorDescriptions.voc,
      },
      {
        icon: <Atom className="w-5 h-5" />,
        name: 'PM 2.5',
        value: '28.5',
        unit: 'µg/m³',
        status: 'Warning',
        description: sensorDescriptions.pm25,
      },
      {
        icon: <Atom className="w-5 h-5" />,
        name: 'PM10',
        value: '48.0',
        unit: 'µg/m³',
        status: 'Warning',
        description: sensorDescriptions.pm10,
      },
      {
        icon: <Droplet className="w-5 h-5" />,
        name: 'Humidity',
        value: '56',
        unit: '%',
        status: 'Good',
        description: sensorDescriptions.humidity,
      },
      {
        icon: <Volume2 className="w-5 h-5" />,
        name: 'Noise',
        value: '68',
        unit: 'dBA',
        status: 'Warning',
        description: sensorDescriptions.noise,
      },
      {
        icon: <Gauge className="w-5 h-5" />,
        name: 'Pressure',
        value: '1014',
        unit: 'hPa',
        status: 'Good',
        description: sensorDescriptions.pressure,
      },
      {
        icon: <Sun className="w-5 h-5" />,
        name: 'Light',
        value: '72',
        unit: '%',
        status: 'Good',
        description: sensorDescriptions.light,
      },
    ],
  },
  wroclaw: {
    name: 'Wrocław',
    sensors: [
      {
        icon: <Thermometer className="w-5 h-5" />,
        name: 'Temp',
        value: '22.0',
        unit: '°C',
        status: 'Good',
        description: sensorDescriptions.temp,
      },
      {
        icon: <Cloud className="w-5 h-5" />,
        name: 'CO₂',
        value: '520',
        unit: 'ppm',
        status: 'Good',
        description: sensorDescriptions.co2,
      },
      {
        icon: <Wind className="w-5 h-5" />,
        name: 'VOC',
        value: '46',
        unit: 'ppb',
        status: 'Good',
        description: sensorDescriptions.voc,
      },
      {
        icon: <Atom className="w-5 h-5" />,
        name: 'PM 2.5',
        value: '15.2',
        unit: 'µg/m³',
        status: 'Good',
        description: sensorDescriptions.pm25,
      },
      {
        icon: <Atom className="w-5 h-5" />,
        name: 'PM10',
        value: '24.1',
        unit: 'µg/m³',
        status: 'Good',
        description: sensorDescriptions.pm10,
      },
      {
        icon: <Droplet className="w-5 h-5" />,
        name: 'Humidity',
        value: '48',
        unit: '%',
        status: 'Good',
        description: sensorDescriptions.humidity,
      },
      {
        icon: <Volume2 className="w-5 h-5" />,
        name: 'Noise',
        value: '59',
        unit: 'dBA',
        status: 'Good',
        description: sensorDescriptions.noise,
      },
      {
        icon: <Gauge className="w-5 h-5" />,
        name: 'Pressure',
        value: '1015',
        unit: 'hPa',
        status: 'Good',
        description: sensorDescriptions.pressure,
      },
      {
        icon: <Sun className="w-5 h-5" />,
        name: 'Light',
        value: '80',
        unit: '%',
        status: 'Good',
        description: sensorDescriptions.light,
      },
    ],
  },
  poznan: {
    name: 'Poznań',
    sensors: [
      {
        icon: <Thermometer className="w-5 h-5" />,
        name: 'Temp',
        value: '20.8',
        unit: '°C',
        status: 'Good',
        description: sensorDescriptions.temp,
      },
      {
        icon: <Cloud className="w-5 h-5" />,
        name: 'CO₂',
        value: '510',
        unit: 'ppm',
        status: 'Good',
        description: sensorDescriptions.co2,
      },
      {
        icon: <Wind className="w-5 h-5" />,
        name: 'VOC',
        value: '44',
        unit: 'ppb',
        status: 'Good',
        description: sensorDescriptions.voc,
      },
      {
        icon: <Atom className="w-5 h-5" />,
        name: 'PM 2.5',
        value: '14.0',
        unit: 'µg/m³',
        status: 'Good',
        description: sensorDescriptions.pm25,
      },
      {
        icon: <Atom className="w-5 h-5" />,
        name: 'PM10',
        value: '22.5',
        unit: 'µg/m³',
        status: 'Good',
        description: sensorDescriptions.pm10,
      },
      {
        icon: <Droplet className="w-5 h-5" />,
        name: 'Humidity',
        value: '50',
        unit: '%',
        status: 'Good',
        description: sensorDescriptions.humidity,
      },
      {
        icon: <Volume2 className="w-5 h-5" />,
        name: 'Noise',
        value: '56',
        unit: 'dBA',
        status: 'Good',
        description: sensorDescriptions.noise,
      },
      {
        icon: <Gauge className="w-5 h-5" />,
        name: 'Pressure',
        value: '1016',
        unit: 'hPa',
        status: 'Good',
        description: sensorDescriptions.pressure,
      },
      {
        icon: <Sun className="w-5 h-5" />,
        name: 'Light',
        value: '76',
        unit: '%',
        status: 'Good',
        description: sensorDescriptions.light,
      },
    ],
  },
  katowice: {
    name: 'Katowice',
    sensors: [
      {
        icon: <Thermometer className="w-5 h-5" />,
        name: 'Temp',
        value: '21.4',
        unit: '°C',
        status: 'Good',
        description: sensorDescriptions.temp,
      },
      {
        icon: <Cloud className="w-5 h-5" />,
        name: 'CO₂',
        value: '590',
        unit: 'ppm',
        status: 'Warning',
        description: sensorDescriptions.co2,
      },
      {
        icon: <Wind className="w-5 h-5" />,
        name: 'VOC',
        value: '68',
        unit: 'ppb',
        status: 'Warning',
        description: sensorDescriptions.voc,
      },
      {
        icon: <Atom className="w-5 h-5" />,
        name: 'PM 2.5',
        value: '26.4',
        unit: 'µg/m³',
        status: 'Warning',
        description: sensorDescriptions.pm25,
      },
      {
        icon: <Atom className="w-5 h-5" />,
        name: 'PM10',
        value: '44.8',
        unit: 'µg/m³',
        status: 'Warning',
        description: sensorDescriptions.pm10,
      },
      {
        icon: <Droplet className="w-5 h-5" />,
        name: 'Humidity',
        value: '54',
        unit: '%',
        status: 'Good',
        description: sensorDescriptions.humidity,
      },
      {
        icon: <Volume2 className="w-5 h-5" />,
        name: 'Noise',
        value: '66',
        unit: 'dBA',
        status: 'Warning',
        description: sensorDescriptions.noise,
      },
      {
        icon: <Gauge className="w-5 h-5" />,
        name: 'Pressure',
        value: '1013',
        unit: 'hPa',
        status: 'Good',
        description: sensorDescriptions.pressure,
      },
      {
        icon: <Sun className="w-5 h-5" />,
        name: 'Light',
        value: '70',
        unit: '%',
        status: 'Good',
        description: sensorDescriptions.light,
      },
    ],
  },
  lodz: {
    name: 'Łódź',
    sensors: [
      {
        icon: <Thermometer className="w-5 h-5" />,
        name: 'Temp',
        value: '20.4',
        unit: '°C',
        status: 'Good',
        description: sensorDescriptions.temp,
      },
      {
        icon: <Cloud className="w-5 h-5" />,
        name: 'CO₂',
        value: '535',
        unit: 'ppm',
        status: 'Good',
        description: sensorDescriptions.co2,
      },
      {
        icon: <Wind className="w-5 h-5" />,
        name: 'VOC',
        value: '51',
        unit: 'ppb',
        status: 'Good',
        description: sensorDescriptions.voc,
      },
      {
        icon: <Atom className="w-5 h-5" />,
        name: 'PM 2.5',
        value: '17.2',
        unit: 'µg/m³',
        status: 'Good',
        description: sensorDescriptions.pm25,
      },
      {
        icon: <Atom className="w-5 h-5" />,
        name: 'PM10',
        value: '28.0',
        unit: 'µg/m³',
        status: 'Good',
        description: sensorDescriptions.pm10,
      },
      {
        icon: <Droplet className="w-5 h-5" />,
        name: 'Humidity',
        value: '51',
        unit: '%',
        status: 'Good',
        description: sensorDescriptions.humidity,
      },
      {
        icon: <Volume2 className="w-5 h-5" />,
        name: 'Noise',
        value: '58',
        unit: 'dBA',
        status: 'Good',
        description: sensorDescriptions.noise,
      },
      {
        icon: <Gauge className="w-5 h-5" />,
        name: 'Pressure',
        value: '1015',
        unit: 'hPa',
        status: 'Good',
        description: sensorDescriptions.pressure,
      },
      {
        icon: <Sun className="w-5 h-5" />,
        name: 'Light',
        value: '74',
        unit: '%',
        status: 'Good',
        description: sensorDescriptions.light,
      },
    ],
  },
  szczecin: {
    name: 'Szczecin',
    sensors: [
      {
        icon: <Thermometer className="w-5 h-5" />,
        name: 'Temp',
        value: '19.0',
        unit: '°C',
        status: 'Good',
        description: sensorDescriptions.temp,
      },
      {
        icon: <Cloud className="w-5 h-5" />,
        name: 'CO₂',
        value: '480',
        unit: 'ppm',
        status: 'Good',
        description: sensorDescriptions.co2,
      },
      {
        icon: <Wind className="w-5 h-5" />,
        name: 'VOC',
        value: '38',
        unit: 'ppb',
        status: 'Good',
        description: sensorDescriptions.voc,
      },
      {
        icon: <Atom className="w-5 h-5" />,
        name: 'PM 2.5',
        value: '10.5',
        unit: 'µg/m³',
        status: 'Good',
        description: sensorDescriptions.pm25,
      },
      {
        icon: <Atom className="w-5 h-5" />,
        name: 'PM10',
        value: '16.2',
        unit: 'µg/m³',
        status: 'Good',
        description: sensorDescriptions.pm10,
      },
      {
        icon: <Droplet className="w-5 h-5" />,
        name: 'Humidity',
        value: '62',
        unit: '%',
        status: 'Good',
        description: sensorDescriptions.humidity,
      },
      {
        icon: <Volume2 className="w-5 h-5" />,
        name: 'Noise',
        value: '53',
        unit: 'dBA',
        status: 'Good',
        description: sensorDescriptions.noise,
      },
      {
        icon: <Gauge className="w-5 h-5" />,
        name: 'Pressure',
        value: '1014',
        unit: 'hPa',
        status: 'Good',
        description: sensorDescriptions.pressure,
      },
      {
        icon: <Sun className="w-5 h-5" />,
        name: 'Light',
        value: '68',
        unit: '%',
        status: 'Good',
        description: sensorDescriptions.light,
      },
    ],
  },
  bydgoszcz: {
    name: 'Bydgoszcz',
    sensors: [
      {
        icon: <Thermometer className="w-5 h-5" />,
        name: 'Temp',
        value: '19.6',
        unit: '°C',
        status: 'Good',
        description: sensorDescriptions.temp,
      },
      {
        icon: <Cloud className="w-5 h-5" />,
        name: 'CO₂',
        value: '505',
        unit: 'ppm',
        status: 'Good',
        description: sensorDescriptions.co2,
      },
      {
        icon: <Wind className="w-5 h-5" />,
        name: 'VOC',
        value: '42',
        unit: 'ppb',
        status: 'Good',
        description: sensorDescriptions.voc,
      },
      {
        icon: <Atom className="w-5 h-5" />,
        name: 'PM 2.5',
        value: '13.1',
        unit: 'µg/m³',
        status: 'Good',
        description: sensorDescriptions.pm25,
      },
      {
        icon: <Atom className="w-5 h-5" />,
        name: 'PM10',
        value: '20.4',
        unit: 'µg/m³',
        status: 'Good',
        description: sensorDescriptions.pm10,
      },
      {
        icon: <Droplet className="w-5 h-5" />,
        name: 'Humidity',
        value: '55',
        unit: '%',
        status: 'Good',
        description: sensorDescriptions.humidity,
      },
      {
        icon: <Volume2 className="w-5 h-5" />,
        name: 'Noise',
        value: '55',
        unit: 'dBA',
        status: 'Good',
        description: sensorDescriptions.noise,
      },
      {
        icon: <Gauge className="w-5 h-5" />,
        name: 'Pressure',
        value: '1015',
        unit: 'hPa',
        status: 'Good',
        description: sensorDescriptions.pressure,
      },
      {
        icon: <Sun className="w-5 h-5" />,
        name: 'Light',
        value: '73',
        unit: '%',
        status: 'Good',
        description: sensorDescriptions.light,
      },
    ],
  },
  lublin: {
    name: 'Lublin',
    sensors: [
      {
        icon: <Thermometer className="w-5 h-5" />,
        name: 'Temp',
        value: '21.0',
        unit: '°C',
        status: 'Good',
        description: sensorDescriptions.temp,
      },
      {
        icon: <Cloud className="w-5 h-5" />,
        name: 'CO₂',
        value: '500',
        unit: 'ppm',
        status: 'Good',
        description: sensorDescriptions.co2,
      },
      {
        icon: <Wind className="w-5 h-5" />,
        name: 'VOC',
        value: '45',
        unit: 'ppb',
        status: 'Good',
        description: sensorDescriptions.voc,
      },
      {
        icon: <Atom className="w-5 h-5" />,
        name: 'PM 2.5',
        value: '14.8',
        unit: 'µg/m³',
        status: 'Good',
        description: sensorDescriptions.pm25,
      },
      {
        icon: <Atom className="w-5 h-5" />,
        name: 'PM10',
        value: '23.0',
        unit: 'µg/m³',
        status: 'Good',
        description: sensorDescriptions.pm10,
      },
      {
        icon: <Droplet className="w-5 h-5" />,
        name: 'Humidity',
        value: '52',
        unit: '%',
        status: 'Good',
        description: sensorDescriptions.humidity,
      },
      {
        icon: <Volume2 className="w-5 h-5" />,
        name: 'Noise',
        value: '54',
        unit: 'dBA',
        status: 'Good',
        description: sensorDescriptions.noise,
      },
      {
        icon: <Gauge className="w-5 h-5" />,
        name: 'Pressure',
        value: '1016',
        unit: 'hPa',
        status: 'Good',
        description: sensorDescriptions.pressure,
      },
      {
        icon: <Sun className="w-5 h-5" />,
        name: 'Light',
        value: '77',
        unit: '%',
        status: 'Good',
        description: sensorDescriptions.light,
      },
    ],
  },
  bialystok: {
    name: 'Białystok',
    sensors: [
      {
        icon: <Thermometer className="w-5 h-5" />,
        name: 'Temp',
        value: '18.8',
        unit: '°C',
        status: 'Good',
        description: sensorDescriptions.temp,
      },
      {
        icon: <Cloud className="w-5 h-5" />,
        name: 'CO₂',
        value: '465',
        unit: 'ppm',
        status: 'Good',
        description: sensorDescriptions.co2,
      },
      {
        icon: <Wind className="w-5 h-5" />,
        name: 'VOC',
        value: '35',
        unit: 'ppb',
        status: 'Good',
        description: sensorDescriptions.voc,
      },
      {
        icon: <Atom className="w-5 h-5" />,
        name: 'PM 2.5',
        value: '9.8',
        unit: 'µg/m³',
        status: 'Good',
        description: sensorDescriptions.pm25,
      },
      {
        icon: <Atom className="w-5 h-5" />,
        name: 'PM10',
        value: '15.0',
        unit: 'µg/m³',
        status: 'Good',
        description: sensorDescriptions.pm10,
      },
      {
        icon: <Droplet className="w-5 h-5" />,
        name: 'Humidity',
        value: '58',
        unit: '%',
        status: 'Good',
        description: sensorDescriptions.humidity,
      },
      {
        icon: <Volume2 className="w-5 h-5" />,
        name: 'Noise',
        value: '48',
        unit: 'dBA',
        status: 'Good',
        description: sensorDescriptions.noise,
      },
      {
        icon: <Gauge className="w-5 h-5" />,
        name: 'Pressure',
        value: '1017',
        unit: 'hPa',
        status: 'Good',
        description: sensorDescriptions.pressure,
      },
      {
        icon: <Sun className="w-5 h-5" />,
        name: 'Light',
        value: '71',
        unit: '%',
        status: 'Good',
        description: sensorDescriptions.light,
      },
    ],
  },
  rzeszow: {
    name: 'Rzeszów',
    sensors: [
      {
        icon: <Thermometer className="w-5 h-5" />,
        name: 'Temp',
        value: '21.5',
        unit: '°C',
        status: 'Good',
        description: sensorDescriptions.temp,
      },
      {
        icon: <Cloud className="w-5 h-5" />,
        name: 'CO₂',
        value: '495',
        unit: 'ppm',
        status: 'Good',
        description: sensorDescriptions.co2,
      },
      {
        icon: <Wind className="w-5 h-5" />,
        name: 'VOC',
        value: '41',
        unit: 'ppb',
        status: 'Good',
        description: sensorDescriptions.voc,
      },
      {
        icon: <Atom className="w-5 h-5" />,
        name: 'PM 2.5',
        value: '13.5',
        unit: 'µg/m³',
        status: 'Good',
        description: sensorDescriptions.pm25,
      },
      {
        icon: <Atom className="w-5 h-5" />,
        name: 'PM10',
        value: '21.8',
        unit: 'µg/m³',
        status: 'Good',
        description: sensorDescriptions.pm10,
      },
      {
        icon: <Droplet className="w-5 h-5" />,
        name: 'Humidity',
        value: '53',
        unit: '%',
        status: 'Good',
        description: sensorDescriptions.humidity,
      },
      {
        icon: <Volume2 className="w-5 h-5" />,
        name: 'Noise',
        value: '56',
        unit: 'dBA',
        status: 'Good',
        description: sensorDescriptions.noise,
      },
      {
        icon: <Gauge className="w-5 h-5" />,
        name: 'Pressure',
        value: '1015',
        unit: 'hPa',
        status: 'Good',
        description: sensorDescriptions.pressure,
      },
      {
        icon: <Sun className="w-5 h-5" />,
        name: 'Light',
        value: '78',
        unit: '%',
        status: 'Good',
        description: sensorDescriptions.light,
      },
    ],
  },
};
